[project]
name = "dedp-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ghp-import>=2.1.0",
    "ipykernel>=6.29.5",
    "jupyter-book>=1.0.4.post0",
]
